---
# tasks file for monitoring
- name: install prometheus
  become: yes
  block:
  - name: Installing tools
    apt:
      name:
        - git
        - curl
      state: present

  - name: Add apt key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add apt repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu focal stable
      state: present

  - name: Installing docker package
    apt:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
      state: present
      update_cache: yes

  - name: Enable docker daemon
    systemd:
      name: docker
      state: started
      enabled: yes

  - name: Install docker-compose
    raw: $(curl -L https://github.com/docker/compose/releases/download/1.29.2/docker-compose-`uname -s`-`uname -m` -o /usr/bin/docker-compose && chmod +x /usr/bin/docker-compose)

  - name: Synchronization
    copy:
      src: stack/
      dest: "/opt/stack/"
      owner: root
      group: root
      mode: 0644
    become: true
  when: '"monitoring" in group_names'

- name: build client list
  block:
  - name: delete all client file
    run_once: true
    delegate_to: localhost
    file:
      path: /tmp/clients
      state: absent 

  - name: build client list
    delegate_to: localhost
    shell: "echo -n \", '{{ ansible_facts.default_ipv4.address }}:9100'\" >> /tmp/clients"
  
  when: '"monitoring" not in group_names'

- name: configure prometheus
  become: yes
  block:
  - name: copy prometeus config
    template:
      src: prometheus.yml.j2
      dest: "/opt/stack/prometheus/prometheus.yml"

  - name: Pull all images in compose
    command: docker-compose -f /opt/stack/docker-compose.yaml pull

  - name: Up all services in compose
    command: docker-compose -f /opt/stack/docker-compose.yaml up -d
  when: '"monitoring" in group_names'

- name: Install clients
  become: yes
  block:
  - name: Upload node exporter service
    template:
      src: node_exporter.service.j2
      dest: /etc/systemd/system/node_exporter.service
      mode: 755

  - name: download node_exporter
    get_url:
      url: https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-amd64.tar.gz
      dest: /tmp/node_exporter.tar.gz

  - name: create folder for node exporter
    file:
      state: directory
      path: "/opt/node_exporter"

  - name: unarchive node_exporter
    unarchive:
      copy: false
      src: /tmp/node_exporter.tar.gz
      dest: /opt/node_exporter
      extra_opts: [--strip-components=1]
      creates: /opt/node_exporter/node_exporter

  - name: start node exporter
    systemd:
      daemon_reload: true
      enabled: true
      name: node_exporter
      state: started
  when: '"monitoring" not in group_names'


