---
# handlers file for gitlab
- name: reconfigure gitlab
  shell: gitlab-ctl reconfigure

- name: register runner
  shell: '/tmp/gitlab-register.sh && touch /tmp/registered'
  args:
    creates: /tmp/registered

- name: commit git repo
  become: false
  shell: 'cd /tmp/wordpress && git add .gitlab-ci.yml && git add * && git commit -m "next commit" && git -c http.sslVerify=false push --set-upstream origin main'
  delegate_to: localhost
