---
# tasks file for wordpress
- name: Install web server
  apt:
    name: 
      - apache2
      - php
      - php-mysql
      - php-json
      - php-soap
      - php-xmlrpc
      - php-mbstring
      - php-xml
      - php-gd
      - php-curl
      - php-intl
      - php-zip
    state: latest
    update_cache: yes

- name: Extract wordpress
  unarchive:
    remote_src: true
    src: https://wordpress.org/latest.tar.gz
    dest: "{{ wordpress_web_root }}"
    extra_opts: [--strip-components=1]

- name: Copy config
  template:
    src: wp-config.php.j2
    dest: "{{ wordpress_web_root }}/wp-config.php"

- name: remove default index.html
  file:
    path: /var/www/html/index.html
    state: absent

- name: Start apache2
  systemd:
    name: apache2
    state: started
